name: Manage APIM Revisions

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Choose the action to perform: "create" for creating a new revision, "activate" for setting a revision as current, "delete" for deleting a revision'
        required: true
        default: 'create'
        options:
          - create
          - activate
          - delete

jobs:
  create-revision:
    if: ${{ github.event.inputs.action == 'create' }}
    runs-on: ubuntu-latest
    steps:
    - name: Log in to Azure
      run: az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
