name: Add API Version to Azure API Management

on:
  push:
    branches:
      - main  # Adjust branch name as needed

jobs:
  add-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install yq
      run: |
        sudo wget https://github.com/mikefarah/yq/releases/download/v4.16.1/yq_linux_amd64 -O /usr/bin/yq
        sudo chmod +x /usr/bin/yq

    - name: Set environment variables for create action
      run: |
        for var in $(yq eval 'keys | .[]' revision/variables/create.yaml); do
          value=$(yq eval ".${var}" revision/variables/create.yaml)
          echo "${var}=${value}" >> $GITHUB_ENV
        done
    - name: Log in to Azure
      run: az login --service-principal -u b68737df-ecf7-47f8-ab56-070ddbf5514c -p e268Q~iD64TpKVLbce.8dydWnALC0nMRkX-vCbzJ --tenant 84f1e4ea-8554-43e1-8709-f0b8589ea118

    - name: Set up Azure CLI
      uses: azure/CLI@v2
      with:
        azcliversion: latest
        inlineScript: |
            az account show

    - name: Add new version to Azure API Management
      run: |
        az apim api versionset create --api-name "${API_NAME}" --resource-group "${API_MANAGEMENT_NAME}" --display-name "Version ${VERSION}" --version "${VERSION}"
      env:
        VERSION: ${{ env.VERSION }}
        API_NAME: ${{ env.API_NAME }}
        API_MANAGEMENT_NAME: ${{ env.API_MANAGEMENT_NAME }}
