name: Create API Version in Azure API Management

on:
  workflow_dispatch:  # Manual trigger

jobs:
  create-api-version:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to Azure
      run: az login --service-principal -u 9231f0ec-8631-4826-a9ee-2a758f70ce63 -p BVR8Q~3sKlpct7mW3uoCbDA5SHeLrfLN_2xq5dbD --tenant 84f1e4ea-8554-43e1-8709-f0b8589ea118

    - name: Set up Azure CLI
      uses: azure/CLI@v2
      with:
        azcliversion: latest
        inlineScript: |
          az account show
        
    - name: Install yq
      run: |
        sudo wget https://github.com/mikefarah/yq/releases/download/v4.16.1/yq_linux_amd64 -O /usr/bin/yq
        sudo chmod +x /usr/bin/yq

    - name: Load variables from YAML
      id: load-variables
      run: |
        variables=$(cat variables/version/create_version.yaml)
        echo "resourceGroupName=$(echo "$variables" | yq eval '.resourceGroupName' -)" >> $GITHUB_ENV
        echo "serviceName=$(echo "$variables" | yq eval '.serviceName' -)" >> $GITHUB_ENV
        echo "sourceApiId=$(echo "$variables" | yq eval '.sourceApiId' -)" >> $GITHUB_ENV
        echo "newApiId=$(echo "$variables" | yq eval '.newApiId' -)" >> $GITHUB_ENV

    - name: Log in to Azure
      run: az login --service-principal -u 9231f0ec-8631-4826-a9ee-2a758f70ce63 -p BVR8Q~3sKlpct7mW3uoCbDA5SHeLrfLN_2xq5dbD --tenant 84f1e4ea-8554-43e1-8709-f0b8589ea118

    - name: Azure PowerShell script
      env:
        resourceGroupName: ${{ env.resourceGroupName }}
        serviceName: ${{ env.serviceName }}
        sourceApiId: ${{ env.sourceApiId }}
      uses: azure/powershell@v2
      with:
        azPSVersion: "latest"
        inlineScript: |
          Connect-AzAccount -ServicePrincipal -Credential (New-Object System.Management.Automation.PSCredential('9231f0ec-8631-4826-a9ee-2a758f70ce63', (ConvertTo-SecureString 'BVR8Q~3sKlpct7mW3uoCbDA5SHeLrfLN_2xq5dbD' -AsPlainText -Force))) -Tenant '84f1e4ea-8554-43e1-8709-f0b8589ea118'
          $context = New-AzApiManagementContext -ResourceGroupName '${{env.resourceGroupName}}' -ServiceName '${{env.serviceName}}'
          $versionSet = Get-AzApiManagementApiVersionSet -Context $context -ApiVersionSetId "6678e9adccb244f33b121b04"
          $sourceApi = Get-AzApiManagementApi -Context $context -ApiId '${{ env.sourceApiId }}'
          $description = $sourceApi.Description
          $serviceUrl = $sourceApi.ServiceUrl
          $path = $sourceApi.Path
          $protocols = $sourceApi.Protocols
          New-AzApiManagementApi -Context $context -Name '${{ env.newApiId }}' -ApiId '${{ env.newApiId }}' -Description $description -SubscriptionRequired -ServiceUrl $serviceUrl -Path $path -Protocols $protocols -ApiVersionSetId $versionSet.ApiVersionSetId -SourceApiId '${{ env.sourceApiId }}' -ApiVersion $env:apiVersion
