name: Manage APIM Revisions

on:
  workflow_dispatch:

jobs:
  create-revision:
    runs-on: ubuntu-latest

    steps:
    - name:  Start the job
      run: echo "Starting the api creation job job"

    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install yq
      run: |
        sudo wget https://github.com/mikefarah/yq/releases/download/v4.16.1/yq_linux_amd64 -O /usr/bin/yq
        sudo chmod +x /usr/bin/yq
        
    - name: Set environment variables for create action src/apisconfig/resource.yaml
      run: |
        for var in $(yq eval 'keys | .[]' src/apisconfig/resource.yaml); do
          value=$(yq eval ".${var}" src/apisconfig/resource.yaml)
          echo "${var}=${value}" >> $GITHUB_ENV
        done
      
    - name: Log in to Azure
      run: az login --service-principal -u 5d0400a1-102b-40ec-8e36-a317f8a44866 -p uuu8Q~4L4a0BbPnQeQ2jPxRbN3cEtryuufj.BbP6 --tenant 84f1e4ea-8554-43e1-8709-f0b8589ea118

    - name: Set up Azure CLI
      uses: azure/CLI@v2
      with:
        azcliversion: latest
        inlineScript: |
            az account show
            
            
    - name: Fetch API Names from File
      run: |
        apis=($(cat ./src/apisconfig/api.txt))
        echo "APIs to create: ${apis[@]}"
        
    - name: Create APIs in Azure API Management  
      run: |
        apis=($(cat ./src/apisconfig/api.txt))
        echo "APIs to create: ${apis[@]}"
        echo "APIs to create: $apis"
        echo "APIs to create: ${apis[@]}"
        for api in "${apis[@]}"; do
          echo "Creat API ID : api $api"
          # Create API Version Set
          # check if the version set exists
          version_set_id_exists=$(az apim api versionset list --resource-group '${{ env.RESOURCE_GROUP }}' --service-name '${{ env.APIM_NAME }}' --query "[?name=='${api}'].id" -o tsv)
          if [[ -z $version_set_id_exists ]]; then
            version_set_id=$(az apim api versionset create  --resource-group '${{ env.RESOURCE_GROUP }}' --service-name '${{ env.APIM_NAME }}' --version-set-id "${api}" --display-name "${api}" --versioning-scheme "Segment" --query "id" -o tsv)
            echo "Created version set ID: $version_set_id"
          else
            version_set_id=$version_set_id_exists
            echo "Version set ID already exists: $version_set_id"
          fi
          version_set_id=$(az apim api versionset create  --resource-group '${{ env.RESOURCE_GROUP }}' --service-name '${{ env.APIM_NAME }}' --version-set-id "${api}" --display-name "${api}" --versioning-scheme "Segment" --query "id" -o tsv)
          echo "Created version set ID: $version_set_id"
          # Import API
          specification_path="./src/apisconfig/specs.json"
          #check if the API exists
          api_exists=$(az apim api list --resource-group '${{ env.RESOURCE_GROUP }}' --service-name '${{ env.APIM_NAME }}' --query "[?name=='${api}'].id" -o tsv)
          if [[ -z $api_exists ]]; then
            az apim api import --resource-group '${{ env.RESOURCE_GROUP }}' --service-name '${{ env.APIM_NAME }}' --specification-format OpenApiJson --specification-path $specification_path --path "openai/deployments/${api}" --display-name "${api}" --api-version '${{ env.REVISION_NUMBER }}' --api-version-set-id "${api}" --api-id "${api}"
            echo "Imported API: $api"
          else
            echo "API already exists: $api"
          fi
          az apim api import --resource-group '${{ env.RESOURCE_GROUP }}' --service-name '${{ env.APIM_NAME }}' --specification-format OpenApiJson --specification-path $specification_path --path "openai/deployments/${api}" --display-name "${api}" --api-version '${{ env.REVISION_NUMBER }}' --api-version-set-id "${api}" --api-id "${api}"
          echo "Imported API: $api"
        done
